In [1]:
import numpy as np
import pandas as pd
from scipy.stats import rankdata, norm, chi2, t
import numpy_indexed as npi

In [103]:
plants = pd.read_csv('../../data/PlantGrowth.csv')
plants = plants.to_numpy()
plants[:3]

array([[1, 4.17, 'ctrl'],
       [2, 5.58, 'ctrl'],
       [3, 5.18, 'ctrl']], dtype=object)

In [104]:
group_obs = np.array([i for _, i in npi.group_by(plants[:, 2], plants[:, 2], len)])

group_medians = []

for i in plants[:, 2]:
    group_medians.append(np.median(plants[np.where(plants[:, 2] == i)][:, 1]))

plants = np.column_stack([plants, np.array(group_medians)])

zij = np.abs(np.array(plants[:, 1] - plants[:, 3]))
plants = np.column_stack([plants, zij])

In [106]:
plants[:5]

array([[1, 4.17, 'ctrl', 5.154999999999999, 0.9849999999999994],
       [2, 5.58, 'ctrl', 5.154999999999999, 0.4250000000000007],
       [3, 5.18, 'ctrl', 5.154999999999999, 0.025000000000000355],
       [4, 6.11, 'ctrl', 5.154999999999999, 0.955000000000001],
       [5, 4.5, 'ctrl', 5.154999999999999, 0.6549999999999994]],
      dtype=object)

In [107]:
zij_group_means = []
for i in plants[:, 2]:
    zij_group_means.append(np.mean(plants[np.where(plants[:, 2] == i)][:, 4]))
plants = np.column_stack([plants, np.array(zij_group_means)])

In [108]:
plants[:5]

array([[1, 4.17, 'ctrl', 5.154999999999999, 0.9849999999999994, 0.442],
       [2, 5.58, 'ctrl', 5.154999999999999, 0.4250000000000007, 0.442],
       [3, 5.18, 'ctrl', 5.154999999999999, 0.025000000000000355, 0.442],
       [4, 6.11, 'ctrl', 5.154999999999999, 0.955000000000001, 0.442],
       [5, 4.5, 'ctrl', 5.154999999999999, 0.6549999999999994, 0.442]],
      dtype=object)

In [109]:
n = plants.shape[0]
k = len(np.unique(plants[:,2]))

In [110]:
zij_group_means = np.array([i for _, i in npi.group_by(plants[:, 2], plants[:, 4], np.mean)])

total_mean = np.mean(plants[:, 4])

num = np.sum(group_obs * (zij_group_means - total_mean) ** 2)

den = np.sum((plants[:, 4] - plants[:, 5]) ** 2)

w = (n - k) / (k - 1) * (num / den)

In [111]:
w

1.1191856948703904

### References

[Snedecor, G. W., & Cochran, W. G. (1989). Statistical methdos (8th ed.). Ames, IA: Iowa State University Press.](https://amzn.to/2UwYNCO)

[Wikipedia contributors. "Levene's test." Wikipedia, The Free Encyclopedia. Wikipedia, The Free Encyclopedia, 28 Apr. 2019. Web. 21 Mar. 2020.](https://en.wikipedia.org/wiki/Levene%27s_test)